apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: az0865s3m-go
  janus-idp.io/tekton: az0865s3m-go
  backstage.io/kubernetes-id: az0865s3m-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: az0865s3m-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
